#!/usr/bin/env python3
"""Build static, indexable EN/TA pages. Standard library only; no network access."""
from pathlib import Path
import json,html,re
from life_template import panel
from urllib.parse import urlparse
P=Path(__file__).resolve().parent;R=P.parent
D=json.loads((P/'content.json').read_text());L=json.loads((P/'locales.json').read_text());esc=lambda x:html.escape(str(x),quote=True)
SLUGS={'en':'people-information-hub.html','ta':'people-information-hub-ta.html'}
assert len({e['id'] for e in D['entries']})==len(D['entries'])
for e in D['entries']:
 assert re.fullmatch('[a-z0-9-]+',e['id']) and e['category'] in L['categories']
 assert all(r in L['regions'] for r in e['regions'])
 for s in e['sources']:assert s in D['sources']
 for lang in SLUGS:
  assert e['title'][lang] and e['summary'][lang] and e['caution'][lang]
  assert all(x[lang] for x in e['steps'])
for s in D['sources'].values():
 assert urlparse(s['url']).scheme=='https' and s['status'] in ['read','limited']
 assert re.fullmatch(r'\d{4}-\d{2}-\d{2}',s['reviewed'])
items=[]
for e in D['entries']:
 items.append({'id':e['id'],'category':e['category'],'regions':e['regions'],'title':e['title'],'askTerms':e.get('askTerms',e['keywords']),'search':' '.join([e['keywords'],*e['title'].values(),*e['summary'].values(),*e['caution'].values(),*[' '.join(v.values()) for v in e['steps']]])})
(P/'data.js').write_text('/* Generated by build.py; edit content.json / locales.json. */\nwindow.PeopleHubData = '+json.dumps({'contact':json.loads((R/'content/site.json').read_text())['whatsapp'],'email':json.loads((R/'content/site.json').read_text())['email'],'items':items,'ui':L['ui'],'categories':L['categories'],'regions':L['regions']},ensure_ascii=False)+';\n')
icons={'today':'01','travel':'02','services':'03','learn':'04','meaning':'05','local':'06'}
for lang,slug in SLUGS.items():
 U=L['ui'][lang];t=lambda k:esc(U[k]);cards=[];seen_categories=set()
 for e in D['entries']:
  sid=e['id']; refs=[]
  category_anchor='' if e['category'] in seen_categories else '<span id="category-'+e['category']+'"></span>'
  seen_categories.add(e['category'])
  for source in e['sources']:
   s=D['sources'][source]
   refs.append(f'<li><a href="{esc(s["url"])}" target="_blank" rel="noopener noreferrer external">{esc(s["name"])} ↗</a><small class="source-domain">{esc(urlparse(s["url"]).hostname)}</small><small class="review" data-reviewed="{s["reviewed"]}">{t("checked")}: <time datetime="{s["reviewed"]}">{s["reviewed"]}</time> · {t("limited" if s["status"]=="limited" else "read")}</small></li>')
  tag=' · '.join(L['regions'][v][lang] for v in e['regions'])
  cards.append(f'''<article class="guide" id="guide-{sid}" data-guide="{sid}" aria-labelledby="title-{sid}">
{category_anchor}<div class="guide-top"><span class="category-label c-{e['category']}">{esc(L['categories'][e['category']][lang])}</span><button type="button" class="save js-control" data-save="{sid}" aria-pressed="false" aria-label="{t('bookmark')}: {esc(e['title'][lang])}" title="{t('bookmark')}" hidden>＋</button></div>
<p class="region-label">{esc(tag)}</p><h3 id="title-{sid}" tabindex="-1">{esc(e['title'][lang])}</h3><p class="summary">{esc(e['summary'][lang])}</p>
<details><summary>{t('steps')} <span aria-hidden="true">↗</span></summary><div class="guide-body"><h4>{t('next')}</h4><ol>{''.join('<li>'+esc(x[lang])+'</li>' for x in e['steps'])}</ol><p class="caution">{esc(e['caution'][lang])}</p><h4>{t('sources')}</h4><ul class="sources">{''.join(refs)}</ul><div class="guide-actions js-control" hidden><button type="button" data-print="{sid}">{t('print')}</button><button type="button" data-copy="{sid}">{t('copy')}</button></div><a class="permalink" href="/{slug}#guide-{sid}">{t('permalink')} ↗</a></div></details></article>''')
 def opts(values):return ''.join('<option value="'+esc(k)+'">'+esc(v[lang])+'</option>' for k,v in values.items())
 cats=''.join(f'<button type="button" data-category="{k}" aria-pressed="false"><span class="category-number" aria-hidden="true">{icons[k]}</span><span>{esc(v[lang])}</span><span class="category-count" data-count="{k}"></span></button>' for k,v in L['categories'].items())
 other='ta' if lang=='en' else 'en'
 page=f'''<!doctype html>
<html lang="{lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="referrer" content="no-referrer"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'self'; style-src 'self'; font-src 'self'; img-src 'self'; connect-src 'none'; object-src 'none'; base-uri 'none'; form-action 'none'"><title>{t('name')} | Podaturpet</title><meta name="description" content="{t('intro')}"><meta name="robots" content="index,follow"><meta name="theme-color" content="#173b3b"><link rel="canonical" href="https://podaturpet.com/{slug}"><link rel="alternate" hreflang="en" href="https://podaturpet.com/{SLUGS['en']}"><link rel="alternate" hreflang="ta" href="https://podaturpet.com/{SLUGS['ta']}"><link rel="alternate" hreflang="x-default" href="https://podaturpet.com/{SLUGS['en']}"><meta property="og:type" content="website"><meta property="og:title" content="{t('name')}"><meta property="og:description" content="{t('intro')}"><meta property="og:url" content="https://podaturpet.com/{slug}"><link rel="icon" href="/people-hub/mark.svg" type="image/svg+xml"><link rel="stylesheet" href="/people-hub/hub.css"><script src="/people-hub/data.js" defer></script><script src="/people-hub/core.js" defer></script><script src="/content/businesses-public.js" defer></script><script src="/people-hub/hub.js" defer></script><script src="/podaturpet-assistant.js" defer></script><script src="/podaturpet-visitor-tracking.js" defer></script></head>
<body><a class="skip" href="#guides">{t('skip')}</a><header class="topbar"><a class="brand" href="/" aria-label="{t('home')}"><img src="/people-hub/mark.svg" width="40" height="40" alt=""><span>PODATURPET<small>{t('name')}</small></span></a><nav aria-label="Language"><a href="/{SLUGS['en']}" lang="en" hreflang="en" {'aria-current="page"' if lang=='en' else ''} data-language="en">English</a><a href="/{SLUGS['ta']}" lang="ta" hreflang="ta" {'aria-current="page"' if lang=='ta' else ''} data-language="ta">தமிழ்</a><button type="button" id="large-text" class="js-control" aria-pressed="false" hidden>{t('large')}</button></nav></header>
<main id="main"><section class="hero"><div class="hero-copy"><p class="eyebrow">{t('eyebrow')}</p><h1>{t('name')}</h1><p class="hero-title">{t('lifeName')}</p><p class="hero-intro">{t('lifeIntro')}</p><p class="hero-intro">{t('intro')}</p><p class="independent">{t('independent')}</p></div><aside class="today-card"><span class="today-dot" aria-hidden="true"></span><h2>{t('dateTitle')}</h2><time id="today-date">{t('deviceClock')}</time><label for="time-zone" class="js-control" hidden>{t('zone')}</label><select id="time-zone" class="js-control" hidden><option value="device">{t('localZone')}</option><option value="Asia/Kolkata">India · Asia/Kolkata</option><option value="America/New_York">New York</option><option value="America/Chicago">Chicago</option><option value="America/Los_Angeles">Los Angeles</option><option value="Europe/London">London</option><option value="Asia/Singapore">Singapore</option><option value="Australia/Sydney">Sydney</option><option value="UTC">UTC</option></select><p class="clock-note">{t('deviceClock')}</p><a href="#category-today">{t('datesLink')}</a><div class="today-bottom"><strong>{t('weekly')}</strong><p>{t('weeklyText')}</p></div></aside></section>
<section id="life-assistant" class="finder js-control" hidden aria-label="{t('search')}"><form id="life-ask-form"><div class="finder-fields"><div class="search-field"><label for="hub-search">{t('search')}</label><input id="hub-search" type="search" maxlength="120" autocomplete="off" spellcheck="false" placeholder="{t('placeholder')}" aria-describedby="search-note"><p id="search-note">{t('askNote')}</p></div><div class="region-field"><label for="region">{t('region')}</label><select id="region" aria-describedby="region-note">{opts(L['regions'])}</select></div></div><button type="submit">{t('ask')}</button></form><div class="life-quick"><button type="button" data-ask="aadhaar">{esc('ஆதார்' if lang=='ta' else 'Aadhaar')}</button><button type="button" data-ask="scholarship">{esc('கல்வி உதவித்தொகை' if lang=='ta' else 'Scholarships')}</button><button type="button" data-ask="overseas recruitment">{esc('வெளிநாட்டு வேலை' if lang=='ta' else 'Overseas work')}</button><button type="button" data-ask="diaspora help">{esc('வெளிநாட்டில் உதவி' if lang=='ta' else 'Diaspora help')}</button></div><div id="life-answer" class="life-answer" role="status" aria-live="polite"></div><button id="life-listen" type="button" hidden>{t('listen')}</button><p class="source-note">{t('voiceNote')}</p><p id="life-voice-status" role="status"></p><p id="region-note">{t('regionHint')}</p><nav class="categories" aria-label="{t('all')}">{cats}</nav><div class="filter-tools"><button type="button" data-category="all" aria-pressed="true">{t('all')}</button><button type="button" id="clear">{t('clear')}</button></div></section>
{panel(t,lang)}
<noscript><p class="notice">{t('noscript')}</p></noscript>
<section class="saved-panel js-control" hidden><div><h2>{t('shelf')} <span id="saved-count">0</span></h2><p>{t('shelfText')}</p></div><div class="saved-controls"><button type="button" id="saved-only" aria-pressed="false">{t('savedOnly')}</button><button type="button" id="persist" aria-pressed="false">{t('persist')}</button><button type="button" id="forget">{t('delete')}</button></div></section>
<p id="message" class="message" role="status" aria-live="polite"></p>
<section id="guides" tabindex="-1"><div class="section-heading"><div><p class="eyebrow">{t('quick')}</p><h2>{t('browse')}</h2></div><div class="js-control" hidden><p id="result-count" role="status" aria-live="polite"></p><button type="button" id="print-visible">{t('printList')}</button></div></div><p class="source-note">{t('sourceNote')}</p><p class="notice" id="stale-notice" hidden>{t('old')}</p><p id="empty" class="empty" hidden>{t('empty')}</p><div class="guide-grid">{''.join(cards)}</div><p class="print-hint">{t('printHint')}</p></section>
<section class="trust-grid"><div><h2>{t('privacyTitle')}</h2><p>{t('privacyText')}</p><a href="/privacy-policy.html">{t('privacyLink')}</a></div><div><h2>{t('disclaimerTitle')}</h2><p>{t('disclaimer')}</p></div></section><section class="more-tools"><h2>{t('ownTools')}</h2><a href="/us-india-family-travel-planner.html">{t('planner')} ↗</a><a href="/free-invoice.html">{t('invoice')} ↗</a><a href="/podaturpet-town-guide.html">{t('localGuide')} ↗</a></section></main><footer><p>{t('footer')}</p><a href="#main">{t('backTop')} ↑</a></footer></body></html>'''
 (R/slug).write_text(page+'\n')
print('Built English and Tamil static pages plus search index')

# Reuse the site presentation layer when regenerating either language.
import sys
sys.path.insert(0,str(Path(__file__).resolve().parents[1]/"tools"))
from site_layout import apply_layout
for slug in SLUGS.values():
 p=Path(__file__).resolve().parents[1]/slug
 p.write_text(apply_layout(p.read_text(),slug))
