"""Original bilingual assistant markup used by the existing static page builder."""
def panel(t,lang):
 def field(name,key,step='0.01',maximum='100000000',minimum='0'):
  return f'<label>{t(key)}<input name="{name}" type="number" inputmode="decimal" min="{minimum}" max="{maximum}" step="{step}" required autocomplete="off"></label>'
 def currency(name,key):
  return f'<label>{t(key)}<select name="{name}">'+''.join(f'<option>{c}</option>' for c in ['INR','USD','GBP','EUR','CAD','AUD','SGD','AED','MYR','LKR'])+'</select></label>'
 edu=currency('currency','currency')+field('tuition','tuition')+field('monthly','monthlyCost')+field('study','study','1','120','1')+field('other','other')+field('funding','funding')+field('save','saveMonths','1','120','1')
 quotes=''.join(f'<fieldset><legend>{t("quote")} {q.upper()}</legend>'+field(q+'fee','fee')+field(q+'rate','rate','0.000001','100000','0.000001')+field(q+'deduction','deduction')+'</fieldset>' for q in ['a','b'])
 areas={'India':'இந்தியா','Tamil Nadu':'தமிழ்நாடு','USA':'அமெரிக்கா','UK':'ஐக்கிய இராச்சியம்','Canada':'கனடா','Australia':'ஆஸ்திரேலியா','Singapore':'சிங்கப்பூர்','Malaysia':'மலேசியா','Sri Lanka':'இலங்கை','Gulf region':'வளைகுடாப் பகுதி','Elsewhere':'வேறு பகுதி'}
 area_options=''.join(f'<option value="{en}">{ta if lang=="ta" else en}</option>' for en,ta in areas.items())
 return f'''<section class="life-tools js-control" id="life-calculators" hidden><p class="eyebrow">02 / {t('plan')}</p><h2>{t('plan')}</h2><p>{t('planNote')}</p><div class="life-tool-grid"><details id="life-education"><summary>{t('education')}</summary><form id="education-form" class="life-form" novalidate>{edu}<button>{t('calculate')}</button><p class="life-result" id="education-result" role="status"></p></form><p>{t('educationFormula')}</p><a href="#guide-education-cost">{t('readSteps')} ↗</a></details><details id="life-remittance"><summary>{t('remittance')}</summary><form id="remittance-form" class="life-form" novalidate>{currency('sender','senderCurrency')}{currency('receiver','receiverCurrency')}{field('budget','budget')}{quotes}<button>{t('calculate')}</button><p class="life-result" id="remittance-result" role="status"></p></form><p>{t('remittanceFormula')}</p><a href="#guide-remittance-quotes">{t('readSteps')} ↗</a></details></div></section>
<section class="life-help js-control" id="life-help" hidden><p class="eyebrow">03 / {t('help')}</p><h2>{t('help')}</h2><p>{t('helpNote')}</p><form id="life-help-form"><div class="life-tool-grid"><label>{t('kind')}<select name="kind"><option value="guide">{t('helpGuide')}</option><option value="local">{t('helpLocal')}</option><option value="business">{t('helpBusiness')}</option></select></label><label>{t('helpRegion')}<select name="area">{area_options}</select></label></div><label>{t('notes')}<textarea name="notes" maxlength="300" rows="3" autocomplete="off" aria-describedby="life-help-privacy"></textarea></label><p id="life-help-privacy">{t('handoffNote')}</p><label class="life-consent"><input type="checkbox" name="consent"> <span>{t('consent')}</span></label><button>{t('preview')}</button><p id="help-status" role="status"></p><div id="help-preview" hidden><pre id="help-message"></pre><a id="help-wa" target="_blank" rel="noopener noreferrer">{t('whatsapp')} ↗</a> <a id="help-email">{t('email')} ↗</a></div></form><p><a href="/podaturpet-local-business-directory.html">{t('directory')} ↗</a> · <a href="/advertise-on-podaturpet.html">{t('advertise')} ↗</a></p></section>
<details class="life-metrics js-control" hidden><summary>{t('metrics')}</summary><p>{t('metricsNote')}</p><label class="life-consent"><input type="checkbox" id="life-count-consent"><span>{t('metricsConsent')}</span></label><dl id="life-counts"></dl><button id="life-count-export" type="button" disabled>{t('exportCounts')}</button><p id="life-count-status" role="status"></p></details>'''
