'use strict';
const form=document.getElementById('invoice-form'),itemsBox=document.getElementById('items'),preview=document.getElementById('preview'),exportButton=document.getElementById('export'),statusBox=document.getElementById('trial-status'),errorBox=document.getElementById('error');
const usageKey='podaturpet.invoice.trial.v1';let logo='',logoBusy=false,exportBusy=false,rowId=0,previewValid=false;
const field=name=>form.elements.namedItem(name);
function showError(message){errorBox.textContent=message||'';errorBox.hidden=!message;}
function usage(){return InvoiceCore.parseUsage(localStorage.getItem(usageKey));}
function availability(){try{const n=usage();localStorage.setItem(usageKey,String(n));statusBox.textContent=n>=3?'Your 3 trial exports are complete. Contact us for continued access.':`${3-n} of 3 trial exports remaining`;exportButton.disabled=n>=3||exportBusy||logoBusy||!previewValid;}catch(e){statusBox.textContent='Trial storage unavailable. Enable browser storage or contact us.';exportButton.disabled=true;}}
function el(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
function addItem(){if(itemsBox.children.length>=50){showError('Maximum 50 items per invoice.');return;}const id=++rowId;const row=el('div',undefined,'item');
row.innerHTML=`<div class="item-head"><strong>Item</strong><button type="button" class="quiet remove">Remove</button></div><label for="desc-${id}">Description<input id="desc-${id}" class="description" required maxlength="300" placeholder="Product or service"></label><div class="two"><label for="qty-${id}">Quantity<input id="qty-${id}" class="quantity" type="number" required min="0.001" max="10000" step="0.001" value="1"></label><label for="price-${id}">Unit price<input id="price-${id}" class="price" type="number" required min="0" max="1000000" step="0.01" value="0.00"></label></div>`;
row.querySelector('.remove').addEventListener('click',()=>{if(itemsBox.children.length===1){showError('Keep at least one item.');return;}row.remove();render();});itemsBox.append(row);render();}
function data(){return [...itemsBox.children].map(row=>({description:row.querySelector('.description').value,quantity:row.querySelector('.quantity').value,price:row.querySelector('.price').value}));}
function render(){try{const entries=data();if(!entries.length)return;const amounts=InvoiceCore.totals(entries,field('discount').value,field('tax').value);const currency=field('currency').value;const money=cents=>new Intl.NumberFormat('en',{style:'currency',currency,currencyDisplay:'code'}).format(cents/100);const doc=document.createDocumentFragment();preview.style.setProperty('--accent',field('accent').value);
const top=el('div',undefined,'inv-top'),business=el('div');if(logo){const img=el('img');img.src=logo;img.alt='Business logo';img.className='inv-logo';business.append(img);}business.append(el('h2',field('business').value||'Your business'),el('div',field('businessDetails').value,'inv-block'));const meta=el('div');meta.append(el('div','INVOICE','inv-title'),el('div',field('number').value||'Invoice number','inv-meta'),el('div','Date: '+field('date').value,'inv-meta'));if(field('due').value)meta.append(el('div','Due: '+field('due').value,'inv-meta'));top.append(business,meta);doc.append(top);
const customer=el('div',undefined,'inv-customer');customer.append(el('small','BILL TO'),el('div',field('customer').value||'Customer name'),el('div',field('customerDetails').value,'inv-block'));doc.append(customer);
const table=el('table'),head=el('thead'),hr=el('tr');['Description','Qty','Unit price','Amount'].forEach((v,i)=>{const h=el('th',v,i?'num':undefined);h.scope='col';hr.append(h);});head.append(hr);table.append(head);const body=el('tbody');entries.forEach((entry,i)=>{const tr=el('tr');tr.append(el('td',entry.description||'Item description'),el('td',entry.quantity,'num'),el('td',money(Math.round(Number(entry.price)*100)),'num'),el('td',money(amounts.lines[i]),'num'));body.append(tr);});table.append(body);doc.append(table);
const totals=el('div',undefined,'inv-totals');[['Subtotal',amounts.subtotal],['Discount',-amounts.discount],[`Tax (${field('tax').value||0}%)`,amounts.tax],['Total',amounts.total]].forEach(([label,value],i)=>{const row=el('div',undefined,'inv-total-row'+(i===3?' grand-total':''));row.append(el('span',label),el('span',money(value)));totals.append(row);});doc.append(totals);
if(field('notes').value){const notes=el('div',undefined,'inv-notes');notes.append(el('small','NOTES / PAYMENT'),el('div',field('notes').value,'inv-block'));doc.append(notes);}preview.replaceChildren(doc);previewValid=true;showError('');}catch(e){previewValid=false;showError(e.message);}availability();}
form.addEventListener('input',render);document.getElementById('add-item').addEventListener('click',addItem);
const logoInput=document.getElementById('logo');let logoVersion=0;
logoInput.addEventListener('change',async()=>{const version=++logoVersion;const file=logoInput.files[0];if(!file)return;logoBusy=true;availability();try{if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>2*1024*1024)throw new Error('Choose a PNG, JPEG or WebP logo under 2 MB.');const reader=new FileReader();const url=await new Promise((resolve,reject)=>{reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(new Error('Could not read this logo.'));reader.readAsDataURL(file);});const img=new Image();await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=()=>reject(new Error('The logo is not a valid image.'));img.src=url;});if(img.width>6000||img.height>6000)throw new Error('Logo dimensions must be at most 6000 × 6000 pixels.');if(version===logoVersion)logo=url;render();}catch(e){showError(e.message);logoInput.value='';}finally{logoBusy=false;availability();}});
document.getElementById('remove-logo').addEventListener('click',()=>{logoVersion++;logo='';logoInput.value='';render();});
form.addEventListener('submit',async event=>{event.preventDefault();if(exportBusy)return;if(!form.reportValidity())return;if(field('due').value&&field('due').value<field('date').value){showError('Due date cannot be before the invoice date.');return;}render();if(!previewValid||logoBusy)return;exportBusy=true;availability();
try{if(!navigator.locks){throw new Error('Please use a current browser that supports this trial tool, or contact us.');}
await navigator.locks.request('podaturpet-invoice-export',()=>{const n=usage();if(n>=3)throw new Error('Your trial is complete. Contact us for continued access.');localStorage.setItem(usageKey,String(n+1));const copy=preview.cloneNode(true);copy.removeAttribute('id');document.getElementById('print-copy').replaceChildren(copy);});
window.print();}catch(e){showError(e.message);}finally{exportBusy=false;availability();}});
window.addEventListener('afterprint',()=>document.getElementById('print-copy').replaceChildren());
window.addEventListener('storage',event=>{if(event.key===usageKey)availability();});
document.getElementById('clear').addEventListener('click',()=>{if(!window.confirm('Clear the invoice details? Your trial count will stay the same.'))return;logoVersion++;logo='';form.reset();itemsBox.replaceChildren();field('date').value=localDate();addItem();});
function localDate(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
field('date').value=localDate();addItem();
