/* Original, dependency-free UI. Deliberately no fetch, analytics or remote assets. */
(function(){'use strict';
const C=TravelCore,content=TravelContent,dict=TravelI18n,KEY='podaturpet.family-travel.v1';
let state=C.defaults(content.packing),dirty=false,active='trip';
const $=id=>document.getElementById(id),text=key=>(dict[key]||[key,key])[state.lang==='ta'?1:0];
function node(tag,value,cls){const n=document.createElement(tag);if(value!==undefined)n.textContent=value;if(cls)n.className=cls;return n;}
function uid(){return 'entry-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,10);}
function say(key,error=false){$('message').textContent=text(key);$('message').hidden=false;$('message').classList.toggle('error',error);}
function changed(){dirty=true;$('save-status').textContent=text('changed');}
function formatDate(s){if(C.day(s)===null)return '—';return new Intl.DateTimeFormat(state.lang==='ta'?'ta-IN':'en-US',{year:'numeric',month:'short',day:'numeric',timeZone:'UTC'}).format(new Date(C.day(s)));}
function currentTasks(){return C.visibleTasks(content.tasks,state.trip);}
function sourceLink(id){if(id==='entry'&&state.trip.direction==='in-us')id='visa';if(id==='customs-india'&&state.trip.direction==='in-us')id='customs-us';const ref=content.sources.find(s=>s.id===id);if(!ref)return node('span');const a=node('a',text('official')+' ↗');a.href=ref.url;a.target='_blank';a.rel='noopener noreferrer';return a;}
function button(key,fn){const b=node('button',text(key));b.type='button';b.addEventListener('click',fn);return b;}
function selectOptions(options,value,fn){const s=node('select');options.forEach(k=>{const o=node('option',text(k));o.value=k;s.append(o);});s.value=value;s.addEventListener('change',()=>fn(s.value));return s;}
function field(key,value,fn,{type='text',max=120}={}){const label=node('label',undefined,'field');label.append(node('span',text(key)));const input=node(type==='textarea'?'textarea':'input');if(type!=='textarea')input.type=type;else input.rows=3;if(type!=='date')input.maxLength=max;input.value=value;input.addEventListener('input',()=>fn(input.value));label.append(input);return label;}
function check(label,value,fn){const l=node('label',undefined,'check-row'),i=node('input');i.type='checkbox';i.checked=value;i.addEventListener('change',()=>fn(i.checked));l.append(i,node('span',label));return l;}
function updateOverview(){const errors=C.tripErrors(state.trip);$('date-errors').replaceChildren(...errors.map(k=>node('p',text(dict[k]?k:'invalidDate'),'alert danger')));const n=C.daysUntil(state.trip.departure);$('countdown').textContent=errors.length?text('validDates'):n===null?text('setDate'):n>0?n+' '+text('daysLeft'):n===0?text('departToday'):text('departed');
const tasks=currentTasks(),done=tasks.filter(t=>state.done[t.id]).length;$('progress-text').textContent=done+' / '+tasks.length;$('progress-bar').max=tasks.length||1;$('progress-bar').value=done;$('progress-bar').setAttribute('aria-label',text('progress'));
const pending=tasks.filter(t=>!state.done[t.id]);$('next-step').textContent=!state.trip.departure?text('tripStart'):pending.length?pending.length+' '+text('remaining'):text('complete');renderAlerts();}
function renderAlerts(){const box=$('document-alerts');box.replaceChildren();if(!state.travelers.length)return;state.travelers.forEach((p,i)=>{const alerts=C.documentAlerts(p,state.trip);if(alerts.length){const block=node('div');block.append(node('strong',p.name||text('traveler')+' '+(i+1)));alerts.forEach(a=>block.append(node('p',text(a.code),'alert '+a.severity)));box.append(block);}});if(!box.children.length)box.append(node('p',text('noAlerts'),'hint'));}
function renderTravelers(){const box=$('travelers');box.replaceChildren();if(!state.travelers.length)box.append(node('p',text('noTravelers'),'hint'));state.travelers.forEach((p,index)=>{const card=node('div',undefined,'entry'),head=node('div',undefined,'entry-head');head.append(node('strong',text('traveler')+' '+(index+1)),button('remove',()=>remove('travelers',p.id)));const grid=node('div',undefined,'entry-grid');const update=(key,val)=>{p[key]=val;changed();updateOverview();};grid.append(field('nickname',p.name,v=>update('name',v),{max:80}),field('passport',p.passport,v=>update('passport',v),{type:'date'}));const mode=node('label',undefined,'field');mode.append(node('span',text('visaMode')),selectOptions(['check','required','none'],p.visaMode,v=>{update('visaMode',v);renderTravelers();}));grid.append(mode);if(p.visaMode==='required')grid.append(field('visa',p.visa,v=>update('visa',v),{type:'date'}));if(state.trip.direction==='in-us')grid.append(field('admitUntil',p.admitUntil,v=>update('admitUntil',v),{type:'date'}));card.append(head,grid);if(state.trip.direction==='in-us')card.append(node('p',text('admitHint'),'hint'));box.append(card);});renderAlerts();}
function renderChecklist(){const box=$('checklist');box.replaceChildren();if(C.tripErrors(state.trip).length){box.append(node('p',text('validDates'),'alert danger'));return;}
const dueOnly=$('due-only').checked;
[30,14,7,3,0,-1].forEach(stage=>{const tasks=currentTasks().filter(t=>t.stage===stage).filter(t=>!dueOnly||(!state.done[t.id]&&['today','overdue'].includes(C.taskStatus(t,state.trip).status)));if(!tasks.length)return;const section=node('section',undefined,'stage'),head=node('div',undefined,'stage-header');const date=C.taskStatus(tasks[0],state.trip).due;head.append(node('h3',text('stage'+stage)),node('small',formatDate(date)));section.append(head);tasks.forEach(t=>{const status=C.taskStatus(t,state.trip),complete=!!state.done[t.id];const row=node('div',undefined,'task '+status.status+(complete?' complete':''));row.append(check(t[state.lang],complete,v=>{state.done[t.id]=v;changed();updateOverview();renderChecklist();}));const meta=node('div',undefined,'task-meta');meta.append(node('span',text(complete?'done':status.status)));if(t.source)meta.append(sourceLink(t.source));row.append(meta);section.append(row);});box.append(section);});if(!box.children.length)box.append(node('p',text('noDue'),'notice'));}
function remove(collection,id){if(!window.confirm(text('confirmRemove')))return;state[collection]=state[collection].filter(p=>p.id!==id);changed();if(collection==='travelers')renderTravelers();else renderLists();updateOverview();}
function renderLists(){const bags=$('packing');bags.replaceChildren();const grid=node('div',undefined,'bag-grid');['personal','carry','checked'].forEach(bag=>{const col=node('div',undefined,'bag-column');col.append(node('h3',text(bag)));state.packing.filter(p=>p.bag===bag).forEach(p=>{const row=node('div',undefined,'pack-row');row.append(check(p[state.lang]||p.en,p.done,v=>{p.done=v;changed();}),button('remove',()=>remove('packing',p.id)));col.append(row);});grid.append(col);});bags.append(grid);
['medicine','gifts'].forEach(collection=>{const box=$(collection);box.replaceChildren();if(!state[collection].length)box.append(node('p',text('empty'),'hint'));state[collection].forEach(p=>{const card=node('div',undefined,'entry'),head=node('div',undefined,'entry-head');head.append(check(text('packed'),p.done,v=>{p.done=v;changed();}),button('remove',()=>remove(collection,p.id)));const fields=node('div',undefined,'entry-grid');function update(k,v){p[k]=v;changed();}fields.append(field(collection==='medicine'?'medicineName':'giftName',p.name,v=>update('name',v),{max:150}),field('quantity',p.quantity,v=>update('quantity',v),{max:40}));if(collection==='medicine')fields.append(field('medicineInstructions',p.note,v=>update('note',v),{type:'textarea',max:300}));else fields.append(field('recipient',p.recipient,v=>update('recipient',v),{max:100}));card.append(head,fields);box.append(card);});});}
function emergencyCard(){const card=node('article',undefined,'emergency-card');card.append(node('div','EMERGENCY TRAVEL CARD · அவசர பயண அட்டை','card-banner'));const body=node('div',undefined,'card-body');const labels={name:'Traveler / பயணி',phone:'My phone / என் எண்',host:'Family contact / குடும்பத் தொடர்பு',hostPhone:'Contact phone / தொடர்பு எண்',address:'Destination / செல்லும் முகவரி',backup:'Backup contact / மாற்றுத் தொடர்பு',help:'Assistance note / உதவிக் குறிப்பு'};const dl=node('dl');Object.entries(labels).forEach(([key,label])=>{const group=node('div',undefined,'card-line');group.append(node('dt',label),node('dd',state.card[key]||'________________'));dl.append(group);});body.append(dl,node('div','USA: 911 · INDIA: 112\nஅவசர உதவிக்கு மட்டும் / Emergencies only','emergency-numbers'),node('p','I may need help communicating. Please contact my family.\nபேசிப் புரியவைக்க எனக்கு உதவி தேவைப்படலாம். என் குடும்பத்தினரைத் தொடர்புகொள்ளுங்கள்.','card-help'));card.append(body);return card;}
function renderCard(){$('emergency-preview').replaceChildren(emergencyCard());}
function renderSources(){$('sources').replaceChildren(...content.sources.map(ref=>{const a=node('a',ref[state.lang]+' ↗','source-link');a.href=ref.url;a.target='_blank';a.rel='noopener noreferrer';return a;}));}
function language(){document.documentElement.lang=state.lang;document.body.classList.toggle('large',state.large);document.querySelectorAll('[data-i18n]').forEach(n=>n.textContent=text(n.dataset.i18n));$('english').setAttribute('aria-pressed',String(state.lang==='en'));$('tamil').setAttribute('aria-pressed',String(state.lang==='ta'));$('large-text').setAttribute('aria-pressed',String(state.large));}
function fillFields(){document.querySelectorAll('[data-group][data-field]').forEach(n=>{const value=state[n.dataset.group][n.dataset.field];if(n.type==='checkbox')n.checked=value;else n.value=value;});}
function renderAll(){language();fillFields();updateOverview();renderTravelers();renderChecklist();renderLists();renderCard();renderSources();}
function validate(){if(C.tripErrors(state.trip).length){say('validDates',true);return false;}try{C.clean(state);return true;}catch(e){say('invalidDate',true);return false;}}
function hasLocal(){try{return localStorage.getItem(KEY)!==null;}catch(e){return false;}}
function download(){if(!validate())return;const blob=new Blob([JSON.stringify(C.clean(state),null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=node('a');a.href=url;a.download='family-travel-plan.json';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);say('exported');}
function planPrint(){const root=node('article');root.append(node('h1',text('title')),node('p',text('disclaimerText'),'print-muted'));const trip=node('section',undefined,'print-section');trip.append(node('h2',state.trip.label||text('tripHeading')));trip.append(node('p',text(state.trip.direction==='us-in'?'toIndia':'toUSA')+' · '+state.trip.from+' → '+state.trip.to));['departure','arrival','returnDate'].forEach(k=>trip.append(node('p',text(k)+': '+formatDate(state.trip[k]))));root.append(trip);
const docs=node('section',undefined,'print-section');docs.append(node('h2',text('travelers')));state.travelers.forEach((p,i)=>{docs.append(node('h3',p.name||text('traveler')+' '+(i+1)),node('p',text('passport')+': '+formatDate(p.passport)),node('p',text('visaMode')+': '+text(p.visaMode)));if(p.visaMode==='required')docs.append(node('p',text('visa')+': '+formatDate(p.visa)));if(state.trip.direction==='in-us'&&p.admitUntil)docs.append(node('p',text('admitUntil')+': '+formatDate(p.admitUntil)));C.documentAlerts(p,state.trip).forEach(a=>docs.append(node('p',text(a.code))));});root.append(docs);
[30,14,7,3,0,-1].forEach(stage=>{const section=node('section',undefined,'print-section');section.append(node('h2',text('stage'+stage)));const list=node('ul');currentTasks().filter(t=>t.stage===stage).forEach(t=>list.append(node('li',(state.done[t.id]?'☑ ':'☐ ')+t[state.lang]+' · '+formatDate(C.taskStatus(t,state.trip).due))));section.append(list);root.append(section);});
['packing','medicine','gifts'].forEach(collection=>{const section=node('section',undefined,'print-section');section.append(node('h2',text(collection==='medicine'?'medicines':collection)));const ul=node('ul');state[collection].forEach(p=>{let value=collection==='packing'?text(p.bag)+': '+(p[state.lang]||p.en):[p.name,p.quantity,collection==='medicine'?p.note:p.recipient].filter(Boolean).join(' · ');ul.append(node('li',(p.done?'☑ ':'☐ ')+value));});section.append(ul);root.append(section);});root.append(emergencyCard());const sources=node('section',undefined,'print-section');sources.append(node('h2',text('sourcesHeading')),node('p',text('sourceNote'),'print-muted'));content.sources.forEach(ref=>sources.append(node('p',ref[state.lang]+'\n'+ref.url,'print-muted')));root.append(sources);return root;}
async function print(mode){if(!validate())return;$('print-output').classList.toggle('card-only',mode==='card');$('print-output').replaceChildren(mode==='card'?emergencyCard():planPrint());if(document.fonts&&document.fonts.ready)await document.fonts.ready;window.print();say('printHint');}
document.querySelectorAll('[data-group][data-field]').forEach(n=>n.addEventListener('input',()=>{state[n.dataset.group][n.dataset.field]=n.type==='checkbox'?n.checked:n.value;changed();if(n.dataset.group==='card')renderCard();else{updateOverview();renderChecklist();if(n.dataset.field==='direction')renderTravelers();}}));
document.querySelectorAll('[data-panel]').forEach(b=>b.addEventListener('click',()=>{active=b.dataset.panel;document.querySelectorAll('.panel').forEach(p=>p.hidden=p.id!=='panel-'+active);document.querySelectorAll('[data-panel]').forEach(n=>n.setAttribute('aria-pressed',String(n===b)));const heading=$('panel-'+active).querySelector('h2');heading.focus();}));
$('english').addEventListener('click',()=>{state.lang='en';changed();renderAll();$('save-status').textContent=text('changed');});$('tamil').addEventListener('click',()=>{state.lang='ta';changed();renderAll();$('save-status').textContent=text('changed');});$('large-text').addEventListener('click',()=>{state.large=!state.large;changed();language();});
$('add-traveler').addEventListener('click',()=>{if(state.travelers.length>=12){say('limit',true);return;}state.travelers.push({id:uid(),name:'',passport:'',visaMode:'check',visa:'',admitUntil:''});changed();renderTravelers();});
$('due-only').addEventListener('change',renderChecklist);
$('add-packing').addEventListener('submit',e=>{e.preventDefault();const form=e.currentTarget,item=form.elements.namedItem('item').value.trim(),bag=form.elements.namedItem('bag').value;if(!item||!form.reportValidity())return;if(state.packing.length>=120){say('limit',true);return;}state.packing.push({id:uid(),en:item,ta:item,bag,done:false});form.elements.namedItem('item').value='';changed();renderLists();});
$('add-medicine').addEventListener('click',()=>{if(state.medicine.length>=60){say('limit',true);return;}state.medicine.push({id:uid(),name:'',note:'',quantity:'',done:false});changed();renderLists();});
$('add-gift').addEventListener('click',()=>{if(state.gifts.length>=80){say('limit',true);return;}state.gifts.push({id:uid(),name:'',recipient:'',quantity:'',done:false});changed();renderLists();});
$('save').addEventListener('click',()=>{if(!validate())return;try{localStorage.setItem(KEY,JSON.stringify(C.clean(state)));dirty=false;$('save-status').textContent=text('saved');say('saved');}catch(e){say('storageFail',true);}});
$('load').addEventListener('click',()=>{try{const raw=localStorage.getItem(KEY);if(raw===null){say('noSaved');return;}const next=C.clean(JSON.parse(raw));if(dirty&&!window.confirm(text('confirmReplace')))return;state=next;dirty=false;renderAll();$('save-status').textContent=text('saved');say('loaded');}catch(e){say(e instanceof SyntaxError||e.message==='schema'||e.message==='date'?'badImport':'storageFail',true);}});
$('delete-saved').addEventListener('click',()=>{if(!window.confirm(text('confirmDelete')))return;try{localStorage.removeItem(KEY);dirty=true;$('save-status').textContent=text('unsaved');say('deleted');}catch(e){say('storageFail',true);}});
$('new-plan').addEventListener('click',()=>{if(!window.confirm(text('confirmReplace')))return;const lang=state.lang,large=state.large;state=C.defaults(content.packing);state.lang=lang;state.large=large;dirty=false;renderAll();$('save-status').textContent=text('unsaved');say('new');});
$('export-json').addEventListener('click',download);
$('import-json').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>300000)throw new Error('size');const next=C.clean(JSON.parse(await file.text()));if(!window.confirm(text('confirmReplace')))return;state=next;changed();renderAll();$('save-status').textContent=text('changed');say('imported');}catch(err){say('badImport',true);}finally{e.target.value='';}});
$('print-plan').addEventListener('click',()=>print('all'));$('print-card').addEventListener('click',()=>print('card'));
window.addEventListener('beforeprint',()=>{if(!$('print-output').children.length)$('print-output').append(planPrint());});window.addEventListener('afterprint',()=>{$('print-output').replaceChildren();$('print-output').classList.remove('card-only');});
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
window.addEventListener('pageshow',()=>{updateOverview();renderChecklist();});document.addEventListener('visibilitychange',()=>{if(!document.hidden){updateOverview();renderChecklist();}});
renderAll();$('save-status').textContent=text('unsaved');if(hasLocal())say('savedExists');
})();
