const {chromium}=require('playwright'),packaged=require('@sparticuz/chromium').default,fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');
(async()=>{const root=path.resolve(__dirname,'../..');const server=http.createServer((req,res)=>{const pathname=decodeURIComponent(req.url.split('?')[0]);const file=path.join(root,pathname==='/'?'index.html':pathname);try{res.setHeader('Content-Type',({'html':'text/html','js':'application/javascript','css':'text/css','svg':'image/svg+xml'})[file.split('.').pop()]||'application/octet-stream');res.end(fs.readFileSync(file));}catch(e){res.statusCode=404;res.end('Not found');}});await new Promise(r=>server.listen(8000,'127.0.0.1',r));const b=await chromium.launch({headless:true,executablePath:await packaged.executablePath(),args:packaged.args});let tests=[];try{
const page=await b.newPage();await page.route('**/*',route=>new URL(route.request().url()).hostname==='127.0.0.1'?route.continue():route.abort());let errors=[];page.on('pageerror',e=>errors.push(e.message));const pages=['index.html','index-ta.html','lungi-product-catalogue.html','wholesale-lungi-enquiry.html','podaturpet-town-guide.html','business-website-development.html','ai-chatbot-development.html','business-workflow-automation.html','advertise-on-podaturpet.html','podaturpet-local-business-directory.html','free-invoice.html','people-information-hub.html','us-india-family-travel-planner.html'];
for(const name of pages){for(const width of [390,1440]){await page.setViewportSize({width,height:900});errors=[];await page.goto('http://127.0.0.1:8000/'+name);await page.waitForTimeout(100);const state=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth,broken:[...document.images].filter(x=>x.complete&&!x.naturalWidth).map(x=>x.getAttribute('src')),h1:document.querySelectorAll('h1').length}));tests.push({page:name,width,...state,errors:[...errors]});} }
await page.goto('http://127.0.0.1:8000/wholesale-lungi-enquiry.html?product=PT-WC-01&private=secret');assert.equal(await page.locator('[name=design]').inputValue(),'PT-WC-01');await page.locator('[name=quantity]').fill('250');await page.locator('[name=destination]').fill('Chennai, India');await page.locator('[name=requirements]').fill('<script>alert(1)</script> sample');await page.locator('#wholesale-enquiry button[type=submit]').click();assert(await page.locator('#buyer-review').isVisible());assert((await page.locator('#buyer-message').innerText()).includes('<script>alert(1)</script>'));assert((await page.locator('#buyer-review a').getAttribute('href')).startsWith('https://wa.me/14793201970?text='));await page.locator('[name=quantity]').fill('300');assert(!(await page.locator('#buyer-review').isVisible()));await page.locator('.site-more-languages summary').click();const url=await page.locator('[data-translate=fr]').getAttribute('href');assert(!url.includes('secret'));await page.keyboard.press('Escape');assert(!(await page.locator('.site-more-languages').getAttribute('open')));tests.push({journey:'Buyer prefill, safe text rendering, WhatsApp draft, stale draft clearing and translation privacy',pass:true});
await page.goto('http://127.0.0.1:8000/index.html');await page.setViewportSize({width:390,height:844});await page.locator('[data-site-language=ta]').click();assert.equal(await page.locator('html').getAttribute('lang'),'ta');await page.goto('http://127.0.0.1:8000/ai-chatbot-development.html');assert.equal(await page.locator('html').getAttribute('lang'),'ta');tests.push({journey:'Tamil preference persists between homepage and AI service',pass:true});await page.locator('[data-site-language=en]').click();await page.goto('http://127.0.0.1:8000/index-ta.html');assert.equal(await page.locator('html').getAttribute('lang'),'ta');tests.push({journey:'Explicit Tamil homepage wins over saved English',pass:true});
const a11y=[];for(const name of ['index.html','index-ta.html','wholesale-lungi-enquiry.html','ai-chatbot-development.html','business-workflow-automation.html']){await page.goto('http://127.0.0.1:8000/'+name);await page.addScriptTag({path:require.resolve('axe-core/axe.min.js')});const results=await page.evaluate(()=>axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}}));a11y.push({page:name,violations:results.violations.map(x=>({id:x.id,impact:x.impact,nodes:x.nodes.map(n=>({target:n.target,summary:n.failureSummary}))}))});}
fs.writeFileSync('browser-test-results.json',JSON.stringify({tests,a11y},null,2));console.log(JSON.stringify({checks:tests.length,failures:tests.filter(x=>x.overflow||x.errors?.length||x.broken?.length||x.h1&&x.h1!==1),a11y},null,2));
await page.goto('http://127.0.0.1:8000/index.html');await page.locator('[data-site-language=en]').click();await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:'homepage-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});await page.screenshot({path:'homepage-mobile.png',fullPage:false});await page.locator('[data-site-language=ta]').click();await page.screenshot({path:'homepage-tamil.png',fullPage:false});
}finally{await b.close();server.close();}})().catch(e=>{console.error(e);process.exit(1)});
