"""Original markup for the existing business-listings region, not a second directory."""
from html import escape as esc
from marketplace_model import dataset

def render(records):
 D=dataset(records);U=D['ui']['ta']
 def t(k,tag='span'):return f'<{tag} data-mkey="{k}">{esc(U[k])}</{tag}>'
 def field(name,key,typ='text',maxlength=80):return f'<label>{t(key)}<input name="{name}" id="market-{name}" type="{typ}" maxlength="{maxlength}" autocomplete="off"></label>'
 def select(name,key,options):return f'<label>{t(key)}<select name="{name}" id="market-{name}">{options}</select></label>'
 services='<option value="" data-mkey="chooseService">'+esc(U['chooseService'])+'</option>'+''.join('<option value="'+s['id']+'">'+esc(s['name']['ta'])+'</option>' for s in D['services'])
 countries='<option value="" data-mkey="chooseCountry">'+esc(U['chooseCountry'])+'</option>'+''.join(f'<option value="{c}">{c}</option>' for c in D['countries'])
 langs='<option value="" data-mkey="anyLanguage">'+esc(U['anyLanguage'])+'</option>'+''.join(f'<option value="{k}">{esc(v["ta"])}</option>' for k,v in D['languages'].items())
 cards=[]
 for p in D['providers']:
  def date_line(key,val):return '<li>'+t(key)+' · <time>'+esc(val)+'</time></li>'
  checks=p['checks'];dates=''.join(date_line(k,checks[j]) for k,j in [('identity','identity_on'),('contactCheck','contact_on'),('scope','scope_on'),('consentCheck','consent_on'),('validUntil','valid_until')])
  licences=''.join('<li>'+t('licence')+' · '+esc(x['country']+' '+x['region']+' · '+x['checked_on'])+' · <a href="'+esc(x['source'],quote=True)+'" target="_blank" rel="noopener noreferrer">'+esc(x['service'])+' ↗</a></li>' for x in checks['licences'])
  areas=' · '.join(a['city']+', '+a['region']+', '+a['country']+' ('+a['mode']+')' for a in p['areas'])
  desc=''.join(f'<p data-provider-lang="{l}"'+(' hidden' if l=='en' else '')+'>'+esc(p['description'][l])+'</p>' for l in ['ta','en'])
  cards.append(f'''<article class="market-provider" data-provider="{p['id']}">{t('sponsored','strong') if p['sponsored'] else ''}<h3>{esc(p['name'])}</h3><p>{esc(areas)}</p><p>{esc(' · '.join(D['languages'][l]['ta']+' / '+D['languages'][l]['en'] for l in p['languages']))}</p><p data-provider-price="{p['id']}">{esc(U['quote'])}</p><details id="provider-{p['id']}" data-provider-profile="{p['id']}"><summary>{t('profile')}</summary>{desc}{t('checks','h4')}<ul>{dates}{licences}</ul><a href="{esc(checks['source'],quote=True)}" target="_blank" rel="noopener noreferrer">{t('identity')} ↗</a>{t('noReviews','p')}{t('priceNote','p')}<button type="button" data-provider-contact="{p['id']}" class="market-js" hidden>{t('contacts')}</button><p><a href="/podaturpet-town-guide.html?contribute=correction#contribute">{t('report')}</a></p></details></article>''')
 fallback='<p class="market-empty" id="market-empty">'+t('noMatches')+'</p>'
 official=''.join('<li><a href="'+esc(D['sources'][reg['source']]['url'],quote=True)+'" target="_blank" rel="noopener noreferrer">'+esc(D['sources'][reg['source']]['name'])+' ↗</a> · '+reg['country']+' '+reg['region']+' · '+t('checked')+' '+D['sources'][reg['source']]['reviewed']+'</li>' for reg in D['registers'])
 return f'''<div id="service-marketplace" class="service-marketplace" lang="ta"><div class="market-heading"><div><p class="market-eyebrow">PODATURPET · GLOBAL SERVICES</p>{t('name','h2')}</div><nav aria-label="Service directory language"><button type="button" data-market-language="ta" aria-pressed="true">தமிழ்</button><button type="button" data-market-language="en" aria-pressed="false">English</button></nav></div>{t('intro','p')}
<form id="market-ask" class="market-js" hidden>{field('question','question',maxlength=180)}<small>Toronto la Tamil accountant venum</small>{t('privacy','p')}<button>{t('understand')}</button></form><p id="market-understood" role="status" aria-live="polite"></p>
<form id="market-search" class="market-js" hidden><div class="market-fields">{select('service','service',services)}{select('country','country',countries)}{field('region','region')}{field('city','city')}{select('language','language',langs)}{select('mode','mode','<option value="local" data-mkey="local">'+U['local']+'</option><option value="remote" data-mkey="remote">'+U['remote']+'</option>')}</div><div class="market-actions"><button>{t('search')}</button><button type="button" id="market-clear">{t('clear')}</button></div></form>
<section id="market-official" class="market-official" aria-labelledby="market-official-title"><h3 id="market-official-title" data-mkey="official">{U['official']}</h3>{t('officialNote','p')}<ul id="market-official-links">{official}</ul></section><p id="market-status" role="status" aria-live="polite"></p>{t('sort','p')}{fallback}<p id="market-empty-help">{t('noMatchesHelp')} <a href="/people-information-hub-ta.html#life-help" id="market-team-help">{t('help')}</a></p><div id="market-results" class="market-results">{''.join(cards)}</div>
<section id="market-contact" class="market-contact" hidden tabindex="-1" aria-labelledby="market-contact-title"><h3 id="market-contact-title" data-mkey="contactTitle">{U['contactTitle']}</h3><p>{t('recipient')}: <strong id="market-recipient"></strong></p><form id="market-contact-form"><label>{t('channel')}<select id="market-channel" name="channel"></select></label><label>{t('note')}<textarea name="note" id="market-note" maxlength="300" rows="3" autocomplete="off"></textarea></label>{t('privacy','p')}{t('guardians','p')}<label class="market-consent"><input type="checkbox" name="consent" id="market-consent">{t('consent')}</label><button>{t('preview')}</button><button type="button" id="market-cancel">{t('cancel')}</button></form><p id="market-contact-status" role="status"></p><div id="market-preview" hidden><pre id="market-message"></pre><p id="market-reference"></p>{t('referenceNote','p')}<a id="market-handoff" data-market-handoff target="_blank" rel="noopener noreferrer">{t('open')} ↗</a>{t('handoff','p')}</div></section>
<p><a href="/podaturpet-town-guide.html?contribute=business#contribute">{t('join')} ↗</a></p>{t('applyNote','p')}<noscript>{t('noScript','p')}</noscript>
<details class="market-metrics market-js" hidden><summary>{t('metrics')}</summary>{t('metricsNote','p')}<label class="market-consent"><input type="checkbox" id="life-count-consent">{t('metricsConsent')}</label><label class="market-consent"><input type="checkbox" id="market-network-consent">{t('networkConsent')}</label><dl id="life-counts"></dl><button type="button" id="life-count-export" disabled>{t('exportCounts')}</button><p id="life-count-status" role="status"></p></details></div>'''
