"""Produce a single ES-module Worker for Cloudflare's browser editor."""
from pathlib import Path
root = Path(__file__).resolve().parent
worker = (root/'worker.mjs').read_text()
pages = (root/'pages.mjs').read_text().replace('export const PAGES', 'const PAGES')
(root/'worker-dashboard.mjs').write_text('// Generated by build-dashboard.py. Edit worker.mjs/pages.mjs, then regenerate.\n'+worker.replace("import { PAGES } from './pages.mjs';", pages))
print('Generated worker-dashboard.mjs')
